from .author_repository_interface import AuthorRepositoryInterface
from .book_author_repository_interface import BookAuthorRepositoryInterface
from .book_repository_interface import BookRepositoryInterface
from .structured_reading_plan_repository_interface import (
    StructuredReadingPlanRepositoryInterface,
)
